config/routes.rb
Rails.application.routes.draw do
  # Root path
  root 'welcome#index'
  
  # Student authentication routes
  get 'students/sign_in', to: 'students/sessions#new', as: 'new_student_session'
  post 'students/sign_in', to: 'students/sessions#create', as: 'student_session'
  delete 'students/sign_out', to: 'students/sessions#destroy', as: 'destroy_student_session'
  
  # Librarian authentication routes
  get 'librarians/sign_in', to: 'librarians/sessions#new', as: 'new_librarian_session'
  post 'librarians/sign_in', to: 'librarians/sessions#create', as: 'librarian_session'
  delete 'librarians/sign_out', to: 'librarians/sessions#destroy', as: 'destroy_librarian_session'
  
  # Admin authentication routes
  get 'admins/sign_in', to: 'admins/sessions#new', as: 'new_admin_session'
  post 'admins/sign_in', to: 'admins/sessions#create', as: 'admin_session'
  delete 'admins/sign_out', to: 'admins/sessions#destroy', as: 'destroy_admin_session'
  
  # Student routes
  resources :students, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Librarian routes
  resources :librarians, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Admin routes
  resources :admins, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Book routes
  resources :books, only: [:index, :show]
  
  # Library routes
  resources :libraries, only: [:index, :show]
  
  # Error pages
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  
  # Catch all routes to 404
  match '*path', to: 'errors#not_found', via: :all

  get 'welcome/index'
  
  # Comment out devise_for routes - they're causing issues in database-free mode
  # devise_for :admins , controllers: { sessions: 'admins/sessions' , registrations: 'admins/registrations'}
  # devise_for :librarians, controllers: { sessions: 'librarians/sessions' , registrations: 'librarians/registrations'}
  # devise_for :students, controllers: { sessions: 'students/sessions' , registrations: 'students/registrations'}
  
  resources :transactions
  resources :home_pages

  get '/search' => 'books#search', :as => 'search'
  get '/checkout' => 'books#checkout', :as => 'checkout'
  get '/returnBook' => 'books#returnBook', :as => 'returnBook'
  get '/repealRequest' => 'books#repealRequest', :as => 'repealRequest'
  get '/bookmark' => 'books#bookmark', :as => 'bookmark'
  get '/unbookmark' => 'books#unbookmark', :as => 'unbookmark'
  get '/requestBook' => 'books#requestBook', :as => 'requestBook'
  get '/student_libraries_index' => 'libraries#student_libraries_index', :as => 'student_libraries_index'

  get '/restricted' => 'librarians#restricted', :as => 'restricted'
  get '/getBookmarkBooks' => 'books#getBookmarkBooks', :as => 'getBookmarkBooks'
  get '/librarian_book_view' => 'books#librarian_book_view', :as => 'librarian_book_view'
  get '/books_students' => 'books#books_students', :as => 'books_students'
  get '/list_checkedoutBooks' => 'books#list_checkedoutBooks', :as => 'list_checkedoutBooks'
  get '/list_checkedoutBooksAndStudentsAdmin' => 'books#list_checkedoutBooksAndStudentsAdmin', :as => 'list_checkedoutBooksAndStudentsAdmin'
  get '/show_librarians' => 'admins#show_librarians', :as => 'show_librarians'
  get '/show_students' => 'admins#show_students', :as => 'show_students'
  get '/show_books' => 'admins#show_books', :as => 'show_books'
  get '/show_libraries' => 'admins#show_libraries', :as => 'show_libraries'
  get '/add_books' => 'books#new', :as => 'add_books'
  get '/add_students' => 'students#new', :as => 'add_students'
  get '/add_librarians' => 'librarians#new', :as => 'add_librarians'
  get '/getStudentBookFine' => 'books#getStudentBookFine', :as => 'getStudentBookFine'
  get '/getOverdueBooks' => 'books#getOverdueBooks', :as => 'getOverdueBooks'
  get '/viewBookHistory' => 'books#viewBookHistory', :as => 'viewBookHistory'
  get '/viewHoldRequestForLibrarian' => 'books#viewHoldRequestForLibrarian', :as => 'viewHoldRequestForLibrarian'
  get '/viewHoldRequestForAdmin' => 'books#viewHoldRequestForAdmin', :as => 'viewHoldRequestForAdmin'
  get '/librarian_special_book' => 'books#librarian_special_book', :as => 'librarian_special_book'
  get '/reject_special_book' => 'books#reject_special_book', :as => 'reject_special_book'
  get '/approve_special_book' => 'books#approve_special_book', :as => 'approve_special_book'
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/add_books.html.erb
<%= render 'form', book: @book %>

app/views/admins/add_librarians.html.erb
<%= render 'form', librarian: @librarian %>

app/views/admins/add_students.html.erb
<%= render 'form', student: @student %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<strong>Note:</strong> Editing your profile will automatically sign you out. You will have to sign back in.
<br>
<br>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Panel</h1>
Name: <%= current_admin.name %><br>
Email: <%=  current_admin.email %><br>
<br>
<br>
<table>
  <th><strong>Admin Rights</strong></th>

  <tr><td><%= link_to 'Edit Profile', edit_admin_path(current_admin) %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Librarians</strong></td><tr>
  <tr><td><%= link_to 'Add Librarian', new_librarian_path %></td></tr>
  <tr><td><%= link_to 'View Librarians (Details/Edit/Delete/Approve)', show_librarians_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Libraries</strong></td><tr>
  <tr><td><%= link_to 'Add Library', new_library_path %></tr>
  <tr><td><%= link_to 'View Libraries (Details/Edit/Delete)', show_libraries_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Students</strong></td><tr>
  <tr><td><%= link_to 'Add Student', new_student_path %></td></tr>
  <tr><td><%= link_to 'View Students (Details/Edit)', show_students_path %></td></tr>  
  <tr><td><%= link_to 'List of Students who have Checked Out Books', list_checkedoutBooksAndStudentsAdmin_path %></td></tr>  
  <tr><td><%= link_to 'View Students with Overdue Fine', getOverdueBooks_path %></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Books</strong></td><tr>
  <tr><td><%= link_to 'Add Book', add_books_path %></td></tr>
  <tr><td><%= link_to 'View Books (Details/Borrowing History/Edit/Delete)', show_books_path %></tr>
  <tr><td><%= link_to 'View Checked Out Books', list_checkedoutBooks_path %></tr>  
  <tr><td><%= link_to 'View Book Hold Request', viewHoldRequestForAdmin_path %></tr>
    
</table>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/admins/show_books.html.erb
<h1>Books</h1>

<%= form_tag(search_path, :method => "get" , :required => true) do %>  
  
  <%= radio_button_tag(:search_by,"title",:checked => true,) %>Title
  <%= radio_button_tag(:search_by, "authors")%>Author
  <%= radio_button_tag(:search_by, "published")%>Published Date
  <%= radio_button_tag(:search_by, "category")%>Category</p>
    <%= search_field_tag :search, params[:search], placeholder: "Search" , :required => true %>  
      <%= button_tag do%> 
	  <%= t('Search')%>
	  <% end %>

<% end %>
<table>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Authors</th>
      <th>Language</th>
      <th>Subject</th>
      <th>Library</th>
      <th>Available Count</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.authors %></td>
        <td><%= book.language %></td>
        <td><%= book.subject %></td>
        <td><%=  Library.find(book.library_id ).name %></td>
        <td><%= book.count %></td>
        <% if current_admin.nil? %>          
          <td><%= link_to 'Checkout', controller: "books", action: "checkout", id: book %></td>
          <td><%= link_to 'Bookmark', controller: "books", action: "bookmark", id: book %></td>
          <td><%= link_to 'Request Book', controller: "books", action: "requestBook", id: book %></td>
        <% else %>
		  <td><%= link_to 'Show', book %></td>
		  <td><%= link_to 'Edit', edit_book_path(book) %></td>
		  <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'View Book History', controller: "books", action: "viewBookHistory", id: book %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/show_librarians.html.erb
<h1>Librarians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Library</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.email %></td>
        <td><%= librarian.library %></td>
        <td><%= librarian.approved %></td>
        <td><%= link_to 'Show', librarian %></td>
        <td><%= link_to 'Edit/Approve', edit_librarian_path(librarian) %></td>
        <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/admins/show_libraries.html.erb
<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>University</th>
      <th>Location</th>
      <th>Borrow limit</th>
      <th>Overdue fines</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= library.university %></td>
        <td><%= library.location %></td>
        <td><%= library.borrow_limit %></td>
        <td><%= library.overdue_fines %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

app/views/admins/show_students.html.erb
<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
		    <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>