config/routes.rb
Rails.application.routes.draw do
  # Root path
  root 'welcome#index'
  
  # Student authentication routes
  get 'students/sign_in', to: 'students/sessions#new', as: 'new_student_session'
  post 'students/sign_in', to: 'students/sessions#create', as: 'student_session'
  delete 'students/sign_out', to: 'students/sessions#destroy', as: 'destroy_student_session'
  
  # Librarian authentication routes
  get 'librarians/sign_in', to: 'librarians/sessions#new', as: 'new_librarian_session'
  post 'librarians/sign_in', to: 'librarians/sessions#create', as: 'librarian_session'
  delete 'librarians/sign_out', to: 'librarians/sessions#destroy', as: 'destroy_librarian_session'
  
  # Admin authentication routes
  get 'admins/sign_in', to: 'admins/sessions#new', as: 'new_admin_session'
  post 'admins/sign_in', to: 'admins/sessions#create', as: 'admin_session'
  delete 'admins/sign_out', to: 'admins/sessions#destroy', as: 'destroy_admin_session'
  
  # Student routes
  resources :students, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Librarian routes
  resources :librarians, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Admin routes
  resources :admins, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Book routes
  resources :books, only: [:index, :show]
  
  # Library routes
  resources :libraries, only: [:index, :show]
  
  # Error pages
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  
  # Catch all routes to 404
  match '*path', to: 'errors#not_found', via: :all

  get 'welcome/index'
  
  # Comment out devise_for routes - they're causing issues in database-free mode
  # devise_for :admins , controllers: { sessions: 'admins/sessions' , registrations: 'admins/registrations'}
  # devise_for :librarians, controllers: { sessions: 'librarians/sessions' , registrations: 'librarians/registrations'}
  # devise_for :students, controllers: { sessions: 'students/sessions' , registrations: 'students/registrations'}
  
  resources :transactions
  resources :home_pages

  get '/search' => 'books#search', :as => 'search'
  get '/checkout' => 'books#checkout', :as => 'checkout'
  get '/returnBook' => 'books#returnBook', :as => 'returnBook'
  get '/repealRequest' => 'books#repealRequest', :as => 'repealRequest'
  get '/bookmark' => 'books#bookmark', :as => 'bookmark'
  get '/unbookmark' => 'books#unbookmark', :as => 'unbookmark'
  get '/requestBook' => 'books#requestBook', :as => 'requestBook'
  get '/student_libraries_index' => 'libraries#student_libraries_index', :as => 'student_libraries_index'

  get '/restricted' => 'librarians#restricted', :as => 'restricted'
  get '/getBookmarkBooks' => 'books#getBookmarkBooks', :as => 'getBookmarkBooks'
  get '/librarian_book_view' => 'books#librarian_book_view', :as => 'librarian_book_view'
  get '/books_students' => 'books#books_students', :as => 'books_students'
  get '/list_checkedoutBooks' => 'books#list_checkedoutBooks', :as => 'list_checkedoutBooks'
  get '/list_checkedoutBooksAndStudentsAdmin' => 'books#list_checkedoutBooksAndStudentsAdmin', :as => 'list_checkedoutBooksAndStudentsAdmin'
  get '/show_librarians' => 'admins#show_librarians', :as => 'show_librarians'
  get '/show_students' => 'admins#show_students', :as => 'show_students'
  get '/show_books' => 'admins#show_books', :as => 'show_books'
  get '/show_libraries' => 'admins#show_libraries', :as => 'show_libraries'
  get '/add_books' => 'books#new', :as => 'add_books'
  get '/add_students' => 'students#new', :as => 'add_students'
  get '/add_librarians' => 'librarians#new', :as => 'add_librarians'
  get '/getStudentBookFine' => 'books#getStudentBookFine', :as => 'getStudentBookFine'
  get '/getOverdueBooks' => 'books#getOverdueBooks', :as => 'getOverdueBooks'
  get '/viewBookHistory' => 'books#viewBookHistory', :as => 'viewBookHistory'
  get '/viewHoldRequestForLibrarian' => 'books#viewHoldRequestForLibrarian', :as => 'viewHoldRequestForLibrarian'
  get '/viewHoldRequestForAdmin' => 'books#viewHoldRequestForAdmin', :as => 'viewHoldRequestForAdmin'
  get '/librarian_special_book' => 'books#librarian_special_book', :as => 'librarian_special_book'
  get '/reject_special_book' => 'books#reject_special_book', :as => 'reject_special_book'
  get '/approve_special_book' => 'books#approve_special_book', :as => 'approve_special_book'
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true
  validates :education_level, presence: true
  validates :university, presence: true
  validates_uniqueness_of :email, confirmation: { case_sensitive: false }
  validates_format_of :email, uniqueness: true, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :password, presence: true, confirmation: true, length: { minimum: 8 }
  
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @student = Student.new
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :password, :education_level, :university, :max_book_allowed])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    '/students'     
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < ApplicationController
  # Skip CSRF verification for the demo
  skip_before_action :verify_authenticity_token
  
  def new
    # Login form
  end
  
  def create
    # Find student by email
    @student = Student.find_by(email: params[:student][:email])
    
    # Check if student exists and password matches
    if @student && @student.valid_password?(params[:student][:password])
      # Set session
      session[:student_id] = @student.id
      
      # Redirect to student dashboard
      redirect_to root_path, notice: "Logged in successfully as student."
    else
      # Show error
      flash.now[:alert] = "Invalid email or password."
      render :new
    end
  end
  
  def destroy
    # Clear session
    session[:student_id] = nil
    
    # Redirect to home page
    redirect_to root_path, notice: "Logged out successfully."
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  #before_action authenticate
  
  # GET /students
  # GET /students.json
  def index
    if admin_signed_in?
      sign_out :student
      redirect_to admins_path
    end
	if librarian_signed_in?
      sign_out :student
      redirect_to librarians_path , notice: 'Action not allowed.'
    end
 
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  if librarian_signed_in?
      sign_out :student
      redirect_to librarians_path , notice: 'Action not allowed.'
    end
  end

  # GET /students/new
  def new
    if librarian_signed_in?
      sign_out :student
      redirect_to librarians_path , notice: 'Action not allowed.'
    else
		@student = Student.new
	end
  end

  # GET /students/1/edit
  def edit
   if librarian_signed_in?
      sign_out :student
      redirect_to librarians_path , notice: 'Action not allowed.'
    end
  end

  # POST /students
  # POST /students.json
  def create
   if librarian_signed_in?
      sign_out :student
      redirect_to librarians_path , notice: 'Action not allowed.'
    else
		@student = Student.new(student_params)

		respond_to do |format|
		  if @student.save
			format.html { redirect_to @student, notice: 'Student was successfully created.' }
			format.json { render :show, status: :created, location: @student }
		  else
			format.html { render :new }
			format.json { render json: @student.errors, status: :unprocessable_entity }
		  end
		end
	end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
  if librarian_signed_in?
      sign_out :student
      redirect_to librarians_path , notice: 'Action not allowed.'
    else
		respond_to do |format|
		  if @student.update(student_params)
			format.html { redirect_to @student, notice: 'Student was successfully updated.' }
			format.json { render :show, status: :ok, location: @student }
		  else
			format.html { render :edit }
			format.json { render json: @student.errors, status: :unprocessable_entity }
		  end
		end
	end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
   if librarian_signed_in?
      sign_out :student
      redirect_to librarians_path , notice: 'Action not allowed.'
    else
		@student.destroy
		if current_admin.nil? 
			respond_to do |format|
			  format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
			  format.json { head :no_content }
			end
		else
			respond_to do |format|
			  format.html { redirect_to show_students_url, notice: 'Student was successfully removed.' }
			  format.json { head :no_content }
			end
		end
	end
  end
  
  def checkoutdisplay
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
	 params.require(:student).permit(:email, :name, :password, :education_level, :university, :max_book_allowed)
    end
  def book_params
    params.require(:book).permit(:isbn, :title, :authors, :language, :published, :edition, :cover, :subject, :summary, :category, :special_collection, :library_id, :count)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :education_level %>
    <%= form.select :education_level, ['B.S.', 'M.S.', 'Ph.D']%>
  </div>

  <div class="field">
    <%= form.label :university %>
    <%= form.select(:university, University::UNIVERSITY_TYPES ) %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_new_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/checkoutdisplay.html.erb
<h1>Your Checked Out Books</h1>

<table>
  <tr>
    <th>Checked Out Books</th>
  </tr>
  <% @checkout.each do |data| %>
    <tr>
      <td><%= data.isbn %></td>
    </tr>
  <% end %>
</table>

<table>
  <tr>
    <th>Bookmarked Books</th>
  </tr>
  <% @request.each do |data| %>
    <tr>
      <td><%= data.isbn %></td>
    </tr>
  <% end %>
</table>


<table>
  <tr>
    <th>Requested Books</th>
  </tr>
  <% @bookmark.each do |data| %>
    <tr>
      <td><%= data.isbn %></td>
    </tr>
  <% end %>
</table>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<strong>Note:</strong> Updating your profile will log you out.<br><br>

<%= render 'new_form', student: @student %>

<% if current_admin.nil? %>
<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>
<% else %>
<%= link_to 'Back', show_students_path %>
<% end %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

Name: <%= current_student.name %><br>
Email: <%=  current_student.email %><br>
<br>
<br>
<table>
  <th><strong>Student Rights</strong></th>
  
  <tr><td></td><tr>
  <tr><td><%= link_to "Edit profile", edit_student_path(current_student) %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Books</strong></td><tr>
  <tr><td><%= link_to 'View Books', books_students_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Libraries</strong></td><tr>
  <tr><td><%= link_to 'View Libraries', student_libraries_index_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Your Data</strong></td><tr>
  <tr><td><%= link_to 'Your Activity (Checkouts/Bookmarks/Hold Requests)', getBookmarkBooks_path %></td></tr>
  <tr><td><%= link_to 'Books Fines', getStudentBookFine_path %></td></tr>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<% if current_admin.nil? %>
<%= link_to 'Back', students_path %>
<% end %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<strong>Note:</strong> Updating your profile has logged you out.<br><br>
<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @student.password %>
</p>

<p>
  <strong>Education level:</strong>
  <%= @student.education_level %>
</p>

<p>
  <strong>University:</strong>
  <%= @student.university %>
</p>

<p>
  <strong>Max book allowed:</strong>
  <%= @student.max_book_allowed %>
</p>


<% if current_admin.nil? %>
	<%= link_to 'Edit', edit_student_path(@student) %> |
	<%= link_to 'Back', new_student_session_path %>
<% else %>
	<%= link_to 'Back', show_students_path %>
<% end %>