config/routes.rb
Rails.application.routes.draw do
  # Root path
  root 'welcome#index'
  
  # Student authentication routes
  get 'students/sign_in', to: 'students/sessions#new', as: 'new_student_session'
  post 'students/sign_in', to: 'students/sessions#create', as: 'student_session'
  delete 'students/sign_out', to: 'students/sessions#destroy', as: 'destroy_student_session'
  
  # Librarian authentication routes
  get 'librarians/sign_in', to: 'librarians/sessions#new', as: 'new_librarian_session'
  post 'librarians/sign_in', to: 'librarians/sessions#create', as: 'librarian_session'
  delete 'librarians/sign_out', to: 'librarians/sessions#destroy', as: 'destroy_librarian_session'
  
  # Admin authentication routes
  get 'admins/sign_in', to: 'admins/sessions#new', as: 'new_admin_session'
  post 'admins/sign_in', to: 'admins/sessions#create', as: 'admin_session'
  delete 'admins/sign_out', to: 'admins/sessions#destroy', as: 'destroy_admin_session'
  
  # Student routes
  resources :students, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Librarian routes
  resources :librarians, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Admin routes
  resources :admins, only: [:index, :show] do
    collection do
      get 'dashboard'
    end
  end
  
  # Book routes
  resources :books, only: [:index, :show]
  
  # Library routes
  resources :libraries, only: [:index, :show]
  
  # Error pages
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  
  # Catch all routes to 404
  match '*path', to: 'errors#not_found', via: :all

  get 'welcome/index'
  
  # Comment out devise_for routes - they're causing issues in database-free mode
  # devise_for :admins , controllers: { sessions: 'admins/sessions' , registrations: 'admins/registrations'}
  # devise_for :librarians, controllers: { sessions: 'librarians/sessions' , registrations: 'librarians/registrations'}
  # devise_for :students, controllers: { sessions: 'students/sessions' , registrations: 'students/registrations'}
  
  resources :transactions
  resources :home_pages

  get '/search' => 'books#search', :as => 'search'
  get '/checkout' => 'books#checkout', :as => 'checkout'
  get '/returnBook' => 'books#returnBook', :as => 'returnBook'
  get '/repealRequest' => 'books#repealRequest', :as => 'repealRequest'
  get '/bookmark' => 'books#bookmark', :as => 'bookmark'
  get '/unbookmark' => 'books#unbookmark', :as => 'unbookmark'
  get '/requestBook' => 'books#requestBook', :as => 'requestBook'
  get '/student_libraries_index' => 'libraries#student_libraries_index', :as => 'student_libraries_index'

  get '/restricted' => 'librarians#restricted', :as => 'restricted'
  get '/getBookmarkBooks' => 'books#getBookmarkBooks', :as => 'getBookmarkBooks'
  get '/librarian_book_view' => 'books#librarian_book_view', :as => 'librarian_book_view'
  get '/books_students' => 'books#books_students', :as => 'books_students'
  get '/list_checkedoutBooks' => 'books#list_checkedoutBooks', :as => 'list_checkedoutBooks'
  get '/list_checkedoutBooksAndStudentsAdmin' => 'books#list_checkedoutBooksAndStudentsAdmin', :as => 'list_checkedoutBooksAndStudentsAdmin'
  get '/show_librarians' => 'admins#show_librarians', :as => 'show_librarians'
  get '/show_students' => 'admins#show_students', :as => 'show_students'
  get '/show_books' => 'admins#show_books', :as => 'show_books'
  get '/show_libraries' => 'admins#show_libraries', :as => 'show_libraries'
  get '/add_books' => 'books#new', :as => 'add_books'
  get '/add_students' => 'students#new', :as => 'add_students'
  get '/add_librarians' => 'librarians#new', :as => 'add_librarians'
  get '/getStudentBookFine' => 'books#getStudentBookFine', :as => 'getStudentBookFine'
  get '/getOverdueBooks' => 'books#getOverdueBooks', :as => 'getOverdueBooks'
  get '/viewBookHistory' => 'books#viewBookHistory', :as => 'viewBookHistory'
  get '/viewHoldRequestForLibrarian' => 'books#viewHoldRequestForLibrarian', :as => 'viewHoldRequestForLibrarian'
  get '/viewHoldRequestForAdmin' => 'books#viewHoldRequestForAdmin', :as => 'viewHoldRequestForAdmin'
  get '/librarian_special_book' => 'books#librarian_special_book', :as => 'librarian_special_book'
  get '/reject_special_book' => 'books#reject_special_book', :as => 'reject_special_book'
  get '/approve_special_book' => 'books#approve_special_book', :as => 'approve_special_book'
end

app/models/librarian.rb
class Librarian < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :library, presence: true
  validates_uniqueness_of :email, confirmation: { case_sensitive: false }
  validates_format_of :email, uniqueness: true, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :password, presence: true, confirmation: true, length: { minimum: 8 }
end

app/controllers/librarians/confirmations_controller.rb
# frozen_string_literal: true

class Librarians::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/librarians/passwords_controller.rb
# frozen_string_literal: true

class Librarians::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/librarians/registrations_controller.rb
# frozen_string_literal: true

class Librarians::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :library, :approved])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
      '/librarians'
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/librarians/sessions_controller.rb
# frozen_string_literal: true

class Librarians::SessionsController < ApplicationController
  # Skip CSRF verification for the demo
  skip_before_action :verify_authenticity_token
  
  def new
    # Login form
  end
  
  def create
    # Find librarian by email
    @librarian = Librarian.find_by(email: params[:librarian][:email])
    
    # Check if librarian exists and password matches
    if @librarian && @librarian.valid_password?(params[:librarian][:password])
      # Set session
      session[:librarian_id] = @librarian.id
      
      # Redirect to librarian dashboard
      redirect_to root_path, notice: "Logged in successfully as librarian."
    else
      # Show error
      flash.now[:alert] = "Invalid email or password."
      render :new
    end
  end
  
  def destroy
    # Clear session
    session[:librarian_id] = nil
    
    # Redirect to home page
    redirect_to root_path, notice: "Logged out successfully."
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/librarians/unlocks_controller.rb
# frozen_string_literal: true

class Librarians::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  #include Accessible
  #before_action authenticate
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]
  
  # def authenticate!
    # if !current_admin.nil? 
        # :authenticate_admin!
	# elsif !current_librarian.nil?
		# :authenticate_librarian!
    # end
  # end

  # GET /librarians
  # GET /librarians.json
  def index
    if admin_signed_in?
      sign_out :librarian
      redirect_to admins_path
	  elsif student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    else
      @lib = Librarian.find_by(:email => current_librarian.email)
      if @lib.approved == 'No'
      redirect_to restricted_path
      else
        library_name = current_librarian.library
        puts library_name
        @library = Library.all.where(:name => library_name).first
        @librarians = Librarian.all
      end
    end
  end
  
  def restricted
  if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    end
  end

  def home_page
  if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    end

  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
  if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    end
  end

  # GET /librarians/new
  def new
  if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    else
		if !current_librarian.nil?
			@lib = Librarian.find_by(:email => current_librarian.email)
			  if @lib.approved == 'No'
				redirect_to restricted_path
			  else
				@librarian = Librarian.new
			  end
		else
			@librarian = Librarian.new
		end
	 end
  end

  # GET /librarians/1/edit
  def edit
  if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    end
  end

  # POST /librarians
  # POST /librarians.json
  def create
  if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    else
		@librarian = Librarian.new(librarian_params)

		respond_to do |format|
		  if @librarian.save
			format.html { redirect_to @librarian, notice: 'Librarian was successfully created.' }
			format.json { render :show, status: :created, location: @librarian }
		  else
			format.html { render :new }
			format.json { render json: @librarian.errors, status: :unprocessable_entity }
		  end
		end
	end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
	if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    else
		respond_to do |format|
		  if @librarian.update(librarian_params)
			format.html { redirect_to @librarian, notice: 'Librarian was successfully updated.' }
			format.json { render :show, status: :ok, location: @librarian }
		  else
			format.html { render :edit }
			format.json { render json: @librarian.errors, status: :unprocessable_entity }
		  end
		end
	end
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
	if student_signed_in?
      sign_out :librarian
      redirect_to students_path, notice: 'Action not allowed.'
    else
		@librarian.destroy
		if current_admin.nil? 
			respond_to do |format|
			  format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
			  format.json { head :no_content }
			end
		else
			respond_to do |format|
			  format.html { redirect_to show_librarians_path, notice: 'Librarian was successfully removed.' }
			  format.json { head :no_content }
			end		
		end
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def librarian_params
      params.require(:librarian).permit(:name, :email, :password, :library, :approved)
    end
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
        <% librarian.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :library %>
    <%= select("librarian", "library", Library.all.collect{ |c| [ c.name] }) %>
  </div>

  <% if current_librarian.nil? %>
	  <div class="field">
		<%= form.label :approved %>
		<%= form.select :approved, ['Yes', 'No']%>
	  </div>
  <% end %>
	
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/edit.html.erb
<h1>Editing Librarian</h1>

<%= render 'form', librarian: @librarian %>

<% if current_admin.nil? %>
<%= link_to 'Show', @librarian %> |
<%= link_to 'Back', librarians_path %>
<% else %>
<%= link_to 'Back', show_librarians_path %>
<% end %>

app/views/librarians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Librarian Panel</h1>
Name: <%= current_librarian.name %><br>
Email: <%=  current_librarian.email %><br>
Library: <%=  current_librarian.library %>&emsp;<%= link_to 'Edit Library Attributes', edit_library_path(@library) %><br>
<br>
<br>
<table>
  <th><strong>Librarian Rights</strong></th>
	<tr><td></tr></td>
	<tr><td></tr></td>
	<tr><td><%= link_to 'Edit Profile', edit_librarian_path(current_librarian) %></td></tr>
	<tr><td></tr></td>
	<tr><td></tr></td>
	<tr><td><strong>Books</strong></tr></td>
	<tr><td><%= link_to 'Add New Book', new_book_path %></td></tr>
	<tr><td><b>To view all books from your as well as other libraries:</b></td></tr>
	<tr><td><%= link_to 'View Books (Details/Edit/Delete/Borrowing History)', librarian_book_view_path %></td></tr>
	<tr><td><%= link_to 'View Checked Out Books', list_checkedoutBooks_path %></td></tr>
	<tr><td><%= link_to 'List of Students who have Checked Out Books', list_checkedoutBooksAndStudentsAdmin_path %></td></tr>  
	<tr><td><%= link_to 'View Overdue Books and Student Fine', getOverdueBooks_path %></td></tr>
	<tr><td><%= link_to 'View Book Hold Request ', viewHoldRequestForLibrarian_path %></td></tr>
	<tr><td><%= link_to 'View special book request', librarian_special_book_path %></td></tr>
	
</table>

app/views/librarians/index_old.html.erb
<p id="notice"><%= notice %></p>

<h1>Librarians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Library</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.email %></td>
        <td><%= librarian.password %></td>
        <td><%= librarian.library %></td>
        <td><%= librarian.approved %></td>
        <td><%= link_to 'Show', librarian %></td>
        <td><%= link_to 'Edit', edit_librarian_path(librarian) %></td>
        <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Librarian', new_librarian_path %>

app/views/librarians/new.html.erb
<h1>New Librarian</h1>

<%= render 'form', librarian: @librarian %>

<% if current_admin.nil? %>
	<%= link_to 'Back', librarians_path %>
<% end %>

app/views/librarians/restricted.html.erb
<p id="notice"><%= notice %></p>

<h1>Librarian Panel</h1>
Name: <%= current_librarian.name %><br>
Email: <%=  current_librarian.email %><br>
<br>
<br>
<table>
    <th><strong>Librarian Rights</strong></th>
	<tr><td></tr></td>
	<tr><td></tr></td>
	<tr><td><%= link_to 'Edit Profile', edit_librarian_path(current_librarian) %></td></tr>
	<tr><td></tr></td>
	<tr><td>Your profile has not been approved yet. Please ask the Administrator to approve it.</tr></td>
</table>

app/views/librarians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @librarian.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @librarian.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @librarian.password %>
</p>

<p>
  <strong>Library:</strong>
  <%= @librarian.library %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @librarian.approved %>
</p>

<%= link_to 'Edit', edit_librarian_path(@librarian) %> |
<%= link_to 'Back', librarians_path %>